# version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8506
    ports:
      - "8506:8506"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: tcpl
      MYSQL_USER: wassan
      MYSQL_PASSWORD: Shizuka1993*
      MYSQL_ROOT_PASSWORD: root  # Add this line
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
