# Generated by Django 5.1.5 on 2025-02-12 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0002_alter_customuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="events",
            name="event_date",
        ),
        migrations.RemoveField(
            model_name="events",
            name="event_description",
        ),
        migrations.RemoveField(
            model_name="events",
            name="event_location",
        ),
        migrations.RemoveField(
            model_name="events",
            name="event_name",
        ),
        migrations.RemoveField(
            model_name="events",
            name="event_time",
        ),
        migrations.AddField(
            model_name="events",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="document",
            field=models.ImageField(blank=True, null=True, upload_to="document/"),
        ),
        migrations.AddField(
            model_name="events",
            name="female_participants",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="from_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="events",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="male_participants",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="organization",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="events",
            name="resource_persons",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="to_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="events",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Meeting", "Meeting"),
                    ("Training", "Training"),
                    ("Exposure Visit", "Exposure Visit"),
                    ("Workshop", "Workshop"),
                    ("Demonstration", "Demonstration"),
                    ("External Visit", "External Visit"),
                    ("Other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
