# Generated by Django 5.1.5 on 2025-02-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0003_remove_events_event_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="document",
            field=models.ImageField(blank=True, null=True, upload_to="documentS/"),
        ),
    ]
