# Generated by Django 5.1.5 on 2025-04-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0003_alter_hhdata_age13_alter_hhdata_age17_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hhdata",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="age13",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="age17",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="age2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="age5",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="age9",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="agriculture",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="are_you_a_member_in_any_institution_yes_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="area_in_ac",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="area_in_ac20",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="area_in_ac25",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="area_in_ac30",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="area_in_ac35",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="area_in_ac41",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="area_in_ac47",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="area_in_ac53",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="area_in_ac59",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="area_in_ac65",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="area_in_ac70",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="area_in_ac75",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="average_price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="average_price23",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="average_price28",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="average_price33",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="average_price38",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="average_price44",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="average_price50",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="average_price56",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="average_price62",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="average_price68",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="average_price72",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="average_price78",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="bank",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="bullocks",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="business",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="column141",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="column142",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="column143",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="column144",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="column145",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="column80",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="column81",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="column82",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="column83",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="column84",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="column85",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="column86",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="column87",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="column88",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="column89",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="column_50000_to_600000",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="contact_no",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="cost",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="cost124",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="cost127",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="cost130",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="cost133",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop74",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_1",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_1111",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_1121",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_1134",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_1146",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_140",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_2",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_2112",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_2122",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_2135",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_2147",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_246",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_3",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_3114",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_3125",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_3138",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_3149",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_352",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_4",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_4116",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_4128",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_4151",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_458",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_5",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_5118",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_5131",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_5153",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_564",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_method_mono_crop_poly_crop",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crop_rotation_yes_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crops",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crops100",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crops104",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crops108",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crops90",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crops94",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="crops97",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="cultivation_fallow_land",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="description",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="description120",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="desi_buffalo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="desi_cow",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="details_of_methods_following",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="details_of_methods_following137",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="details_of_methods_following140",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="domestic_drinking_purpose",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="education",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="female",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="fertilizers_shop",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="fertlizers_per_ac",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="following_methods",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="following_methods103",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="following_methods107",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="following_methods110",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="following_methods93",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="following_methods96",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="following_methods99",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="following_yes_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="following_yes_no_136",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="following_yes_no_139",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="gender",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="gender10",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="gender14",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="gender18",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="gender3",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="gender6",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="head_of_the_family",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="hf_cow",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="if_exist_year_of_ewxcavation",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="if_yes_shg_pacs_fpo",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="in_which_month_water_availability_becomes_low",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="interest_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="investment",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="investment102",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="investment106",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="investment109",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="investment92",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="investment95",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="investment98",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="irrigation_methods_followed",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="irrigation_methods_followed113",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="irrigation_methods_followed115",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="irrigation_methods_followed117",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="irrigation_methods_followed119",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="is_there_farm_pond_in_the_field_yes_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="job",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="labour_work",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="land_type_ups_and_downs_plane",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="main_crop",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="male",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="manure_per_ac",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="manure_per_ac101",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="manure_per_ac105",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="manure_per_ac91",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="market",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="market_148",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="market_150",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="market_152",
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="market_154",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="milch_animals",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="money_lendors",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="mono_crop_poly_crop",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="murra_buffalo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="name_12",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="name_16",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="name_4",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="name_8",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="neighbours_relations",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="normal_salty_medium_salt_low_salt",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="other_sources",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="own_bore_public_bore_dug_well_pipeline",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="pacs",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="per_ac",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="purchase_at_vendors_yes_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="purchase_at_vendors_yes_no_123",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="purchase_at_vendors_yes_no_126",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="purchase_at_vendors_yes_no_129",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="purchase_at_vendors_yes_no_132",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="purchase_of_seeds_from_vendors",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="rainfed_irrigated",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="rainfed_irrigated21",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="rainfed_irrigated26",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="rainfed_irrigated31",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="rainfed_irrigated36",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="rainfed_irrigated42",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="rainfed_irrigated48",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="rainfed_irrigated54",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="rainfed_irrigated60",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="rainfed_irrigated66",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="rainfed_irrigated71",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="rainfed_irrigated76",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="relation_with_family_head",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="relation_with_family_head11",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="relation_with_family_head15",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="relation_with_family_head19",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="relation_with_family_head7",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="s_no",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="sc_st_bc_oc",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="seed_cost",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="seeds_grow_yourself",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="sheep_goat_byp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="silt_per_ac",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="size",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="soil_depth_in_cm",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="soil_name_local",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="source_1",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="source_2",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="source_3",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="total",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="total_income",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="total_income24",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="total_income29",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="total_income34",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="total_income39",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="total_income45",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="total_income51",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="total_income57",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="total_income63",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="total_income69",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="total_income73",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="total_income79",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="total_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="total_percentage_100",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="village",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="vo",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="was_the_farm_pond_dug_irrigation_ground_water_fisheries_others",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="water_source",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="yield_kg_ac",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="yield_kg_ac_77",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="yield_qtl_ac",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="yield_qtl_ac_22",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="yield_qtl_ac_27",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="yield_qtl_ac_32",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="yield_qtl_ac_37",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="yield_qtl_ac_43",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="yield_qtl_ac_49",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="yield_qtl_ac_55",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="yield_qtl_ac_61",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hhdata",
            name="yield_qtl_ac_67",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
