# Generated by Django 5.1.5 on 2025-05-08 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0004_alter_hhdata_age_alter_hhdata_age13_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="geomap",
            fields=[
                ("map_id", models.AutoField(primary_key=True, serialize=False)),
                ("map_name", models.CharField(blank=True, max_length=100, null=True)),
                ("geodata", models.FileField(blank=True, null=True, upload_to="maps/")),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
