# Generated by Django 5.1.5 on 2025-02-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0004_alter_events_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="document",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
    ]
