# Generated by Django 5.1.5 on 2025-02-14 12:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0005_alter_events_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                ("gallary_id", models.AutoField(primary_key=True, serialize=False)),
                ("activity", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Photos", "Photos"),
                            ("Videos", "Videos"),
                            ("Media Coverage", "Media Coverage"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resources",
            fields=[
                ("resource_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IEC Material", "IEC Material"),
                            ("Training Modules", "Training Modules"),
                            ("Training Material", "Training Material"),
                            ("Reports", "Reports"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("contact_no", models.PositiveIntegerField(blank=True, null=True)),
                ("email_id", models.EmailField(blank=True, max_length=50, null=True)),
                (
                    "work_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
