# Generated by Django 5.1.5 on 2025-02-14 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0006_gallery_resources_team"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gallery",
            old_name="gallary_id",
            new_name="gallery_id",
        ),
    ]
