# Generated by Django 5.1.5 on 2025-02-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0007_rename_gallary_id_gallery_gallery_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="document",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
