# Generated by Django 5.1.5 on 2025-03-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0008_alter_gallery_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="event_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="total_participants",
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name="events",
            name="female_participants",
            field=models.IntegerField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name="events",
            name="male_participants",
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
