# Generated by Django 5.1.5 on 2025-03-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0009_events_event_name_events_total_participants_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="female_participants",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="events",
            name="male_participants",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="events",
            name="total_participants",
            field=models.IntegerField(default=0),
        ),
    ]
