import pandas as pd
import os
import django
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'test_project.settings')


django.setup()


from test_app.models import hhdata

# Load Excel
df = pd.read_excel('C:/Users/WASSAN/OneDrive/git projects/django/test_project/jalodhari besline reports.xlsx', sheet_name='Direct Beneficiaries HH')  # Update path
df.columns = df.columns.str.strip()
df = df.map(lambda x: x.strip() if isinstance(x, str) else x)
df = df.fillna(0)  # Convert NaN to None



for _, row in df.iterrows():
    try:
        
        hhdata.objects.create(
            s_no=row['S.No'],
            village=row['Village'],
            head_of_the_family=row['Head of the Family'],
            age=row['Age'],
            gender=row['Gender'],
            contact_no=row['Contact No'],
            sc_st_bc_oc=row['SC/ST/BC/OC'],
            education=row['Education'],
            male=row['Male'],
            female=row['Female'],
            total=row['Total'],
            name=row['Name'],
            age2=row['Age2'],
            gender3=row['Gender3'],
            relation_with_family_head=row['Relation with family head'],
            name_4=row['Name 4'],
            age5=row['Age5'],
            gender6=row['Gender6'],
            relation_with_family_head7=row['Relation with family head7'],
            name_8=row['Name 8'],
            age9=row['Age9'],
            gender10=row['Gender10'],
            relation_with_family_head11=row['Relation with family head11'],
            name_12=row['Name 12'],
            age13=row['Age13'],
            gender14=row['Gender14'],
            relation_with_family_head15=row['Relation with family head15'],
            name_16=row['Name 16'],
            age17=row['Age17'],
            gender18=row['Gender18'],
            relation_with_family_head19=row['Relation with family head19'],
            own_bore_public_bore_dug_well_pipeline=row['Own bore/public bore/Dug well/Pipeline'],
            normal_salty_medium_salt_low_salt=row['Normal/Salty/Medium salt/Low salt'],
            in_which_month_water_availability_becomes_low=row['In which month water availability becomes low'],
            domestic_drinking_purpose=row['Domestic & Drinking purpose'],
            column_50000_to_600000=row['50000 to 600000'],
            agriculture=row['Agriculture'],
            milch_animals=row['Milch Animals'],
            sheep_goat_byp=row['Sheep, Goat & BYP'],
            bullocks=row['Bullocks'],
            labour_work=row['Labour work'],
            job=row['Job'],
            business=row['Business'],
            other_sources=row['Other sources'],
            total_percentage_100=row['Total Percentage 100'],
            are_you_a_member_in_any_institution_yes_no=row['Are you a member in any institution (Yes/No)'],
            if_yes_shg_pacs_fpo=row['IF Yes (SHG/PACS/FPO)'],
            vo=row['VO'],
            bank=row['Bank'],
            pacs=row['PACS'],
            fertilizers_shop=row['Fertilizers Shop'],
            money_lendors=row['Money lendors'],
            neighbours_relations=row['Neighbours/Relations'],
            total_percentage=row['Total Percentage'],
            interest_rate=row['Interest rate'],
            land_type_ups_and_downs_plane=row['Land Type (Ups and downs/Plane)'],
            soil_name_local=row['Soil Name (Local)'],
            soil_depth_in_cm=row['Soil depth in Cm'],
            cultivation_fallow_land=row['Cultivation/Fallow land'],
            main_crop=row['Main Crop'],
            mono_crop_poly_crop=row['Mono crop/Poly crop'],
            water_source=row['Water Source'],
            crop_1=row['Crop-1'],
            area_in_ac=row['Area in Ac'],
            rainfed_irrigated=row['Rainfed/Irrigated'],
            yield_qtl_ac=row['Yield (Qtl/Ac)'],
            average_price=row['Average Price'],
            total_income=row['Total Income'],
            crop_2=row['Crop-2'],
            area_in_ac20=row['Area in Ac20'],
            rainfed_irrigated21=row['Rainfed/Irrigated21'],
            yield_qtl_ac_22=row['Yield (Qtl/Ac)22'],
            average_price23=row['Average Price23'],
            total_income24=row['Total Income24'],
            crop_3=row['Crop-3'],
            area_in_ac25=row['Area in Ac25'],
            rainfed_irrigated26=row['Rainfed/Irrigated26'],
            yield_qtl_ac_27=row['Yield (Qtl/Ac)27'],
            average_price28=row['Average Price28'],
            total_income29=row['Total Income29'],
            crop_4=row['Crop-4'],
            area_in_ac30=row['Area in Ac30'],
            rainfed_irrigated31=row['Rainfed/Irrigated31'],
            yield_qtl_ac_32=row['Yield (Qtl/Ac)32'],
            average_price33=row['Average Price33'],
            total_income34=row['Total Income34'],
            crop_5=row['Crop-5'],
            area_in_ac35=row['Area in Ac35'],
            rainfed_irrigated36=row['Rainfed/Irrigated36'],
            yield_qtl_ac_37=row['Yield (Qtl/Ac)37'],
            average_price38=row['Average Price38'],
            total_income39=row['Total Income39'],
            crop_140=row['Crop-140'],
            area_in_ac41=row['Area in Ac41'],
            rainfed_irrigated42=row['Rainfed/Irrigated42'],
            yield_qtl_ac_43=row['Yield (Qtl/Ac)43'],
            average_price44=row['Average Price44'],
            total_income45=row['Total Income45'],
            crop_246=row['Crop-246'],
            area_in_ac47=row['Area in Ac47'],
            rainfed_irrigated48=row['Rainfed/Irrigated48'],
            yield_qtl_ac_49=row['Yield (Qtl/Ac)49'],
            average_price50=row['Average Price50'],
            total_income51=row['Total Income51'],
            crop_352=row['Crop-352'],
            area_in_ac53=row['Area in Ac53'],
            rainfed_irrigated54=row['Rainfed/Irrigated54'],
            yield_qtl_ac_55=row['Yield (Qtl/Ac)55'],
            average_price56=row['Average Price56'],
            total_income57=row['Total Income57'],
            crop_458=row['Crop-458'],
            area_in_ac59=row['Area in Ac59'],
            rainfed_irrigated60=row['Rainfed/Irrigated60'],
            yield_qtl_ac_61=row['Yield (Qtl/Ac)61'],
            average_price62=row['Average Price62'],
            total_income63=row['Total Income63'],
            crop_564=row['Crop-564'],
            area_in_ac65=row['Area in Ac65'],
            rainfed_irrigated66=row['Rainfed/Irrigated66'],
            yield_qtl_ac_67=row['Yield (Qtl/Ac)67'],
            average_price68=row['Average Price68'],
            total_income69=row['Total Income69'],
            crop=row['Crop'],
            area_in_ac70=row['Area in Ac70'],
            rainfed_irrigated71=row['Rainfed/Irrigated71'],
            yield_kg_ac=row['Yield (Kg/Ac)'],
            average_price72=row['Average Price72'],
            total_income73=row['Total Income73'],
            crop74=row['Crop74'],
            area_in_ac75=row['Area in Ac75'],
            rainfed_irrigated76=row['Rainfed/Irrigated76'],
            yield_kg_ac_77=row['Yield (Kg/Ac)77'],
            average_price78=row['Average Price78'],
            total_income79=row['Total Income79'],
            source_1=row['Source-1'],
            source_2=row['Source-2'],
            source_3=row['Source-3'],
            column80=row['Column80'],
            column81=row['Column81'],
            column82=row['Column82'],
            column83=row['Column83'],
            column84=row['Column84'],
            column85=row['Column85'],
            column86=row['Column86'],
            column87=row['Column87'],
            column88=row['Column88'],
            column89=row['Column89'],
            crops=row['Crops'],
            manure_per_ac=row['Manure per Ac'],
            investment=row['Investment'],
            following_methods=row['Following Methods'],
            crops90=row['Crops90'],
            manure_per_ac91=row['Manure per Ac91'],
            investment92=row['Investment92'],
            following_methods93=row['Following Methods93'],
            crops94=row['Crops94'],
            silt_per_ac=row['Silt per Ac'],
            investment95=row['Investment95'],
            following_methods96=row['Following Methods96'],
            crops97=row['Crops97'],
            fertlizers_per_ac=row['Fertlizers per Ac'],
            investment98=row['Investment98'],
            following_methods99=row['Following Methods99'],
            crops100=row['Crops100'],
            manure_per_ac101=row['Manure per Ac101'],
            investment102=row['Investment102'],
            following_methods103=row['Following Methods103'],
            crops104=row['Crops104'],
            manure_per_ac105=row['Manure per Ac105'],
            investment106=row['Investment106'],
            following_methods107=row['Following Methods107'],
            crops108=row['Crops108'],
            per_ac=row['per Ac'],
            investment109=row['Investment109'],
            following_methods110=row['Following Methods110'],
            crop_1111=row['Crop-1111'],
            irrigation_methods_followed=row['Irrigation methods followed'],
            crop_2112=row['Crop-2112'],
            irrigation_methods_followed113=row['Irrigation methods followed113'],
            crop_3114=row['Crop-3114'],
            irrigation_methods_followed115=row['Irrigation methods followed115'],
            crop_4116=row['Crop-4116'],
            irrigation_methods_followed117=row['Irrigation methods followed117'],
            crop_5118=row['Crop-5118'],
            irrigation_methods_followed119=row['Irrigation methods followed119'],
            is_there_farm_pond_in_the_field_yes_no=row['Is there farm pond in the field (Yes/No)'],
            if_exist_year_of_ewxcavation=row['If exist, year of ewxcavation'],
            size=row['Size'],
            was_the_farm_pond_dug_irrigation_ground_water_fisheries_others=row['Why was the farm pond dug (Irrigation/Ground water/fisheries/others)'],
            crop_rotation_yes_no=row['Crop Rotation (Yes/No)'],
            description=row['Description'],
            crop_method_mono_crop_poly_crop=row['Crop Method (Mono crop/Poly crop)'],
            description120=row['Description120'],
            seeds_grow_yourself=row['Seeds grow yourself'],
            purchase_of_seeds_from_vendors=row['Purchase of seeds from vendors %'],
            seed_cost=row['Seed cost'],
            crop_1121=row['Crop-1121'],
            purchase_at_vendors_yes_no=row['Purchase at vendors (Yes/No)'],
            cost=row['Cost'],
            crop_2122=row['Crop-2122'],
            purchase_at_vendors_yes_no_123=row['Purchase at vendors (Yes/No)123'],
            cost124=row['Cost124'],
            crop_3125=row['Crop-3125'],
            purchase_at_vendors_yes_no_126=row['Purchase at vendors (Yes/No)126'],
            cost127=row['Cost127'],
            crop_4128=row['Crop-4128'],
            purchase_at_vendors_yes_no_129=row['Purchase at vendors (Yes/No)129'],
            cost130=row['Cost130'],
            crop_5131=row['Crop-5131'],
            purchase_at_vendors_yes_no_132=row['Purchase at vendors (Yes/No)132'],
            cost133=row['Cost133'],
            crop_1134=row['Crop-1134'],
            following_yes_no=row['Following (Yes/No)'],
            details_of_methods_following=row['Details of methods following'],
            crop_2135=row['Crop-2135'],
            following_yes_no_136=row['Following (Yes/No)136'],
            details_of_methods_following137=row['Details of methods following137'],
            crop_3138=row['Crop-3138'],
            following_yes_no_139=row['Following (Yes/No)139'],
            details_of_methods_following140=row['Details of methods following140'],
            column141=row['Column141'],
            desi_cow=row['Desi Cow'],
            hf_cow=row['HF Cow'],
            desi_buffalo=row['Desi Buffalo'],
            murra_buffalo=row['Murra Buffalo'],
            column142=row['Column142'],
            column143=row['Column143'],
            column144=row['Column144'],
            column145=row['Column145'],
            crop_1146=row['Crop-1146'],
            market=row['Market'],
            crop_2147=row['Crop-2147'],
            market_148=row['Market 148'],
            crop_3149=row['Crop-3149'],
            market_150=row['Market 150'],
            crop_4151=row['Crop-4151'],
            market_152=row['Market 152'],
            crop_5153=row['Crop-5153'],
            market_154=row['Market 154']
        )
    except Exception as e:
        print(f"Error creating record for row {row['S.No']}: {e}")
